version: '3'
services:
  kong:
    image: ahmetyuksel/kong
    container_name: kong
    network_mode: host
    user: kong
#    command: kong migrations bootstrap  //uncomment for first migration only
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_DATABASE: postgres
      KONG_PG_HOST: $(pg_host)
      KONG_PG_DATABASE: $(pg_db_name_kong)
      KONG_PG_USER: $(pg_user_kong)
      KONG_PG_PASSWORD: $(pg_pass_kong)
      LOG_LEVEL: debug
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure

  konga:
    image: ahmetyuksel/konga
    container_name: konga
    network_mode: host
    environment:
      TOKEN_SECRET: geraltofrivia
      DB_ADAPTER: postgres
      DB_HOST: $(pg_host)
      DB_DATABASE: $(pg_db_name_konga)
      DB_USER: $(pg_user_konga)
      DB_PASSWORD: $(pg_pass_konga)
    ports:
      - "1337:1337/tcp"
    restart: always
